onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp3_tb/clk
add wave -noupdate /mp3_tb/dut/cpu/mem_resp
add wave -noupdate -radix hexadecimal /mp3_tb/dut/cpu/mem_rdata
add wave -noupdate /mp3_tb/dut/cpu/mem_read
add wave -noupdate -radix hexadecimal /mp3_tb/dut/cpu/mem_write
add wave -noupdate /mp3_tb/dut/cpu/mem_byte_enable
add wave -noupdate -radix hexadecimal /mp3_tb/dut/cpu/mem_address
add wave -noupdate -radix hexadecimal /mp3_tb/dut/cpu/mem_wdata
add wave -noupdate /mp3_tb/pmem_resp
add wave -noupdate /mp3_tb/pmem_read
add wave -noupdate /mp3_tb/pmem_write
add wave -noupdate -radix hexadecimal /mp3_tb/pmem_address
add wave -noupdate -radix hexadecimal /mp3_tb/pmem_wdata
add wave -noupdate -radix hexadecimal /mp3_tb/pmem_rdata
add wave -noupdate /mp3_tb/write_data
add wave -noupdate /mp3_tb/write_address
add wave -noupdate /mp3_tb/write
add wave -noupdate /mp3_tb/halt
add wave -noupdate -childformat {{{/mp3_tb/dut/cache/datapath/data_array0/data[7]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[6]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[5]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[4]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[3]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[2]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[1]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array0/data[0]} -radix hexadecimal}} -subitemconfig {{/mp3_tb/dut/cache/datapath/data_array0/data[7]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[6]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[5]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[4]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[3]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[2]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[1]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array0/data[0]} {-radix hexadecimal}} /mp3_tb/dut/cache/datapath/data_array0/data
add wave -noupdate -childformat {{{/mp3_tb/dut/cache/datapath/data_array1/data[7]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[6]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[5]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[4]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[3]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[2]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[1]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/data_array1/data[0]} -radix hexadecimal}} -subitemconfig {{/mp3_tb/dut/cache/datapath/data_array1/data[7]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[6]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[5]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[4]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[3]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[2]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[1]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/data_array1/data[0]} {-radix hexadecimal}} /mp3_tb/dut/cache/datapath/data_array1/data
add wave -noupdate -childformat {{{/mp3_tb/dut/cache/datapath/tag_array0/data[7]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[6]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[5]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[4]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[3]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[2]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[1]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array0/data[0]} -radix hexadecimal}} -subitemconfig {{/mp3_tb/dut/cache/datapath/tag_array0/data[7]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[6]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[5]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[4]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[3]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[2]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[1]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array0/data[0]} {-radix hexadecimal}} /mp3_tb/dut/cache/datapath/tag_array0/data
add wave -noupdate -childformat {{{/mp3_tb/dut/cache/datapath/tag_array1/data[7]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[6]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[5]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[4]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[3]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[2]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[1]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/tag_array1/data[0]} -radix hexadecimal}} -subitemconfig {{/mp3_tb/dut/cache/datapath/tag_array1/data[7]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[6]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[5]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[4]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[3]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[2]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[1]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/tag_array1/data[0]} {-radix hexadecimal}} /mp3_tb/dut/cache/datapath/tag_array1/data
add wave -noupdate -childformat {{{/mp3_tb/dut/cache/datapath/LRU_array/data[7]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[6]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[5]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[4]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[3]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[2]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[1]} -radix hexadecimal} {{/mp3_tb/dut/cache/datapath/LRU_array/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/mp3_tb/dut/cache/datapath/LRU_array/data[7]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[6]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[5]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[4]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[3]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[2]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[1]} {-radix hexadecimal} {/mp3_tb/dut/cache/datapath/LRU_array/data[0]} {-radix hexadecimal}} /mp3_tb/dut/cache/datapath/LRU_array/data
add wave -noupdate -childformat {{{/mp3_tb/registers[0]} -radix hexadecimal} {{/mp3_tb/registers[1]} -radix hexadecimal} {{/mp3_tb/registers[2]} -radix hexadecimal} {{/mp3_tb/registers[3]} -radix hexadecimal} {{/mp3_tb/registers[4]} -radix hexadecimal} {{/mp3_tb/registers[5]} -radix hexadecimal} {{/mp3_tb/registers[6]} -radix hexadecimal} {{/mp3_tb/registers[7]} -radix hexadecimal} {{/mp3_tb/registers[8]} -radix hexadecimal} {{/mp3_tb/registers[9]} -radix hexadecimal} {{/mp3_tb/registers[10]} -radix hexadecimal} {{/mp3_tb/registers[11]} -radix hexadecimal} {{/mp3_tb/registers[12]} -radix hexadecimal} {{/mp3_tb/registers[13]} -radix hexadecimal} {{/mp3_tb/registers[14]} -radix hexadecimal} {{/mp3_tb/registers[15]} -radix hexadecimal} {{/mp3_tb/registers[16]} -radix hexadecimal} {{/mp3_tb/registers[17]} -radix hexadecimal} {{/mp3_tb/registers[18]} -radix hexadecimal} {{/mp3_tb/registers[19]} -radix hexadecimal} {{/mp3_tb/registers[20]} -radix hexadecimal} {{/mp3_tb/registers[21]} -radix hexadecimal} {{/mp3_tb/registers[22]} -radix hexadecimal} {{/mp3_tb/registers[23]} -radix hexadecimal} {{/mp3_tb/registers[24]} -radix hexadecimal} {{/mp3_tb/registers[25]} -radix hexadecimal} {{/mp3_tb/registers[26]} -radix hexadecimal} {{/mp3_tb/registers[27]} -radix hexadecimal} {{/mp3_tb/registers[28]} -radix hexadecimal} {{/mp3_tb/registers[29]} -radix hexadecimal} {{/mp3_tb/registers[30]} -radix hexadecimal} {{/mp3_tb/registers[31]} -radix hexadecimal}} -subitemconfig {{/mp3_tb/registers[0]} {-radix hexadecimal} {/mp3_tb/registers[1]} {-radix hexadecimal} {/mp3_tb/registers[2]} {-radix hexadecimal} {/mp3_tb/registers[3]} {-radix hexadecimal} {/mp3_tb/registers[4]} {-radix hexadecimal} {/mp3_tb/registers[5]} {-radix hexadecimal} {/mp3_tb/registers[6]} {-radix hexadecimal} {/mp3_tb/registers[7]} {-radix hexadecimal} {/mp3_tb/registers[8]} {-radix hexadecimal} {/mp3_tb/registers[9]} {-radix hexadecimal} {/mp3_tb/registers[10]} {-radix hexadecimal} {/mp3_tb/registers[11]} {-radix hexadecimal} {/mp3_tb/registers[12]} {-radix hexadecimal} {/mp3_tb/registers[13]} {-radix hexadecimal} {/mp3_tb/registers[14]} {-radix hexadecimal} {/mp3_tb/registers[15]} {-radix hexadecimal} {/mp3_tb/registers[16]} {-radix hexadecimal} {/mp3_tb/registers[17]} {-radix hexadecimal} {/mp3_tb/registers[18]} {-radix hexadecimal} {/mp3_tb/registers[19]} {-radix hexadecimal} {/mp3_tb/registers[20]} {-radix hexadecimal} {/mp3_tb/registers[21]} {-radix hexadecimal} {/mp3_tb/registers[22]} {-radix hexadecimal} {/mp3_tb/registers[23]} {-radix hexadecimal} {/mp3_tb/registers[24]} {-radix hexadecimal} {/mp3_tb/registers[25]} {-radix hexadecimal} {/mp3_tb/registers[26]} {-radix hexadecimal} {/mp3_tb/registers[27]} {-radix hexadecimal} {/mp3_tb/registers[28]} {-radix hexadecimal} {/mp3_tb/registers[29]} {-radix hexadecimal} {/mp3_tb/registers[30]} {-radix hexadecimal} {/mp3_tb/registers[31]} {-radix hexadecimal}} /mp3_tb/registers
add wave -noupdate /mp3_tb/dut/cpu/control/state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {199549 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 247
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {199050 ps} {199990 ps}
